### ISSUE TITLE
What does this error mean?

### ISSUE THREAD

**Issue by NIULQfromNJU** [VerbalExpressions/CppVerbalExpressions#7]
i have finished installing boost library, running cmake and make, but when i run  CppVerbalExpressionsExample, i got following error:

terminate called after throwing an instance of 'std::regex_error'
  what():  regex_error
Aborted

**Comment by NIULQfromNJU** [comment]
I found  ver*.hpp used std::regex instead of boost::regex because USE_BOOST is undefined, how to fix this problem?

#ifdef USE_BOOST
#include <boost/regex.hpp>
namespace veregex = boost;
#else
#include <regx> 
namespace veregex = std;
#endif

**Comment by whackashoe** [comment]
Put `#define USE_BOOST` somewhere above `#ifdef USE_BOOST`.

You can either set this right before `#include "verbalexpressions.hpp" or in verbalexpressions.hpp itself.

**Comment by NIULQfromNJU** [comment]
Solved！
Thanks~
