### ISSUE TITLE
how can we get

### ISSUE THREAD

**Issue by dry11orange** [VerbalExpressions/CppVerbalExpressions#9]
we can test and replace
but how can we get the match part from the source string

**Comment by whackashoe** [comment]
Apologies for late reply, didn't see this until now. 

Can you be more specific? What are you trying to do?

**Comment by dry11orange** [comment]
RegularExpression re("([0-9]+) ([0-9]+)");
	std::string s = "123 456";
	assert (re.subst(s, "$2-$1") == 1);
	assert (s == "456-123");

like this,$1, $2
we can get the match subpart form the source string, so we can use it

and another problem
how can we use match "\\"

**Comment by whackashoe** [comment]
This doesn't support what you want to do, however you can do the same thing using the `veregex` namespace which will use either std or boost based on your config. Look at the `bool test(const std::string & value)` function for how you could do so. If you think of a nice api to use I'd be happy to include it in this library. Maybe there could be an `std::vector<std::string> extract(const std::string & value)` function added? 

---

For matching "\\" you need to double escape like so:

```
    verex expr = verex()          
                .search_one_line()
                .start_of_line()
                .then( "\\\\" )
                .end_of_line();
    
    std::cout << (expr.test("\\") ? "matches" : "doesn't match") << std::endl;
```

**Comment by dry11orange** [comment]
thank you very much.

and

RegularExpression re("([0-9]+) ([0-9]+)");
std::string s = "123 456";
assert (re.subst(s, "$2-$1") == 1);
assert (s == "456-123");

code like this,it's from Poco which implement with lot Dependency.
So I can't add it to your library easily.

**Comment by whackashoe** [comment]
Sure, but same thing could be achieved with the standard.. 

I do really like your suggestion, this _should_ support what you want to do. If I come up with api change I'll ping you :+1:

**Comment by dry11orange** [comment]
en.
just ping(do) me(it)!
